import { StyleSheet } from 'react-native';
import { colors } from '../../shared/theme/tokens';

// 작성자: 김진우 — 검수 화면의 정보 계층과 입력 영역을 통일한다.
export const reviewStyles = StyleSheet.create({
  section: { gap: 12 },
  headingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 8,
    marginBottom: 2,
  },
  heading: { flex: 1, fontSize: 19, fontWeight: '800', color: colors.text },
  count: {
    backgroundColor: '#E9F2EE',
    color: '#426658',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
    fontSize: 12,
    fontWeight: '700',
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E3ECE7',
    padding: 20,
    gap: 14,
    boxShadow: '0px 4px 12px rgba(23, 58, 49, 0.035)',
  },
  title: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 24,
  },
  label: { fontSize: 12, color: '#667A71', fontWeight: '600', marginBottom: 7 },
  valueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F4F8F6',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E5EDE8',
    minHeight: 62,
    paddingHorizontal: 16,
    gap: 12,
  },
  input: {
    flex: 1,
    minWidth: 0,
    minHeight: 60,
    paddingVertical: 12,
    color: colors.text,
    fontSize: 24,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  textInput: { fontSize: 17, fontWeight: '600' },
  focused: { borderColor: colors.primaryDark, backgroundColor: '#F0F9F4' },
  unit: {
    flexShrink: 1,
    maxWidth: '40%',
    fontSize: 14,
    lineHeight: 20,
    color: '#61766C',
    fontWeight: '600',
  },
  statusRow: {
    borderTopWidth: 1,
    borderTopColor: '#EDF2EF',
    paddingTop: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    alignItems: 'baseline',
  },
  statusLabel: { fontSize: 12, color: '#73867D' },
  status: { fontSize: 13, lineHeight: 20, color: '#445F52', flexShrink: 1 },
  radioRow: { flexDirection: 'row', gap: 10 },
  radio: {
    flex: 1,
    minHeight: 52,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    padding: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E1E9E4',
    backgroundColor: '#F8FAF9',
  },
  radioSelected: { borderColor: '#2B8465', backgroundColor: '#EAF5EE' },
  radioText: { fontSize: 15, fontWeight: '700', color: '#6A7D73' },
  radioSelectedText: { color: '#236B50' },
  radioDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#A9B9B0',
  },
  radioDotSelected: { borderWidth: 5, borderColor: '#2B8465' },
  disabled: { opacity: 0.5 },
  warning: {
    fontSize: 12,
    lineHeight: 19,
    color: '#956327',
    backgroundColor: '#FFF7EA',
    padding: 10,
    borderRadius: 10,
  },
  exceptionCard: { backgroundColor: '#FFFCF6', borderColor: '#EBDCC1' },
  exceptionAction: {
    minHeight: 44,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D8C6A9',
    alignItems: 'center',
  },
  exceptionText: { color: '#805D2E', fontSize: 13, fontWeight: '700' },
  intro: { backgroundColor: '#EAF4EE', borderRadius: 24, padding: 22, gap: 10 },
  eyebrow: {
    fontSize: 11,
    letterSpacing: 1.2,
    color: '#4B7964',
    fontWeight: '800',
  },
  introTitle: {
    color: colors.text,
    fontSize: 26,
    lineHeight: 35,
    fontWeight: '800',
  },
  introDescription: { color: '#577466', fontSize: 14, lineHeight: 23 },
});
