import { StyleSheet } from 'react-native';
import { colors } from '../../shared/theme/tokens';
// 작성자: 김진우 — 내 건강의 요약·그래프·입력·검진 화면에 밝은 표면과 일관된 높이감을 적용한다.
export const hs = StyleSheet.create({
  root: { flex: 1, minHeight: 0 },
  content: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 28,
    gap: 16,
    width: '100%',
    maxWidth: 480,
    alignSelf: 'center',
  },
  row: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  // 작성자: 고수연 — 수치 카드 줄. 기록일 줄은 예전 기록일 때만 생기므로 카드 높이가
  // 서로 달라진다. stretch 로 한 줄 안에서 높이를 맞춘다.
  metricRow: { flexDirection: 'row', alignItems: 'stretch', gap: 10 },
  between: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  title: { fontSize: 23, fontWeight: '800', color: colors.text },
  section: { fontSize: 15, fontWeight: '700', color: colors.text },
  text: { fontSize: 13, lineHeight: 20, color: colors.text },
  muted: { fontSize: 11, lineHeight: 17, color: colors.textMuted },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 24,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: '#DCEEEB',
    borderTopColor: '#FFFFFF',
    boxShadow:
      '0px 8px 18px rgba(34, 131, 145, 0.12), 0px 2px 3px rgba(34, 131, 145, 0.05)',
  },
  pill: {
    minHeight: 40,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 22,
    backgroundColor: '#F7FFFC',
    borderWidth: 1,
    borderColor: '#D8EEE6',
    boxShadow: '0px 3px 6px rgba(35, 133, 126, 0.10)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  active: {
    backgroundColor: '#1AB894',
    borderColor: '#64DABC',
    boxShadow: '0px 4px 9px rgba(21, 173, 137, 0.24)',
  },
  pillText: { fontSize: 12, fontWeight: '700', color: colors.primaryDark },
  white: { color: '#FFFFFF' },
  metric: {
    flex: 1,
    minWidth: 0,
    padding: 16,
    borderRadius: 24,
    backgroundColor: colors.surface,
    gap: 12,
    borderWidth: 1,
    borderColor: '#D8EEEA',
    borderTopColor: '#FFFFFF',
    boxShadow:
      '0px 8px 18px rgba(46, 128, 166, 0.14), 0px 2px 3px rgba(46, 128, 166, 0.05)',
  },
  metricIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#FFFFFF',
    boxShadow: '0px 4px 8px rgba(56, 139, 166, 0.15)',
  },
  metricLabel: {
    fontSize: 11,
    color: '#77918F',
    fontWeight: '600',
    flexShrink: 1,
    textAlign: 'right',
  },
  metricUnit: { fontSize: 11, color: '#93A6A3', fontWeight: '500' },
  // 작성자: 고수연 — 숫자와 단위를 한 덩어리로 묶는다. '7시간 30분'이 두 쌍으로 붙는다.
  metricAmount: {
    flexDirection: 'row' as const,
    alignItems: 'baseline' as const,
    gap: 2,
  },
  metricDate: { fontSize: 9, color: '#A0B0AD', letterSpacing: 0.2 },
  syncNotice: {
    fontSize: 11,
    lineHeight: 17,
    color: '#72948E',
    paddingHorizontal: 4,
  },
  value: { fontSize: 28, fontWeight: '800', color: colors.primaryDark },
  // 작성자: 김진우 — 작은 단위의 줄 높이가 섭취량 숫자를 자르지 않도록 별도로 배치한다.
  waterRecordAmount: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 5,
  },
  waterRecordValue: { lineHeight: 38, includeFontPadding: true },
  error: { fontSize: 12, lineHeight: 18, color: colors.danger },
  input: {
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 18,
    padding: 14,
    fontSize: 16,
    color: colors.text,
    backgroundColor: '#F4FAFC',
    boxShadow: 'inset 0px 2px 4px rgba(45, 113, 137, 0.06)',
    minHeight: 48,
  },
  field: { gap: 7, flex: 1 },
  spacer: { flex: 1 },
  back: {
    minWidth: 36,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backText: { fontSize: 30, color: colors.text },
  surface: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 23,
  },
  domain: { minHeight: 80 },
  domainIcon: {
    width: 46,
    height: 46,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#FFFFFF',
    boxShadow: '0px 4px 8px rgba(47, 123, 151, 0.14)',
  },
  pressed: { transform: [{ scale: 0.985 }], opacity: 0.9 },
});
