// 작성자: 김진우 — 영역별 추천 카드의 색상과 모든 조회 상태의 공통 스타일.
import { StyleSheet } from 'react-native';
import { colors } from '../../shared/theme/tokens';

export const recommendationThemes: Record<
  string,
  { label: string; color: string; tint: string }
> = {
  BIO: { label: '신체 건강', color: '#187C61', tint: '#EAF7F0' },
  ACTIVITY: { label: '활동', color: '#356DC1', tint: '#EDF4FF' },
  NUTRITION: { label: '영양', color: '#A85835', tint: '#FFF2E9' },
  HYDRATION: { label: '수분', color: '#356DC1', tint: '#EDF4FF' },
  SLEEP: { label: '수면', color: '#7653B5', tint: '#F3EEFC' },
  CHECKUP: { label: '건강검진', color: '#187C61', tint: '#EAF7F0' },
};

export const recommendationStyles = StyleSheet.create({
  card: {
    borderRadius: 28,
    padding: 24,
    gap: 20,
    borderWidth: 1,
    borderColor: '#E5EDE9',
    boxShadow: '0px 6px 22px rgba(23,58,49,0.05)',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    flexWrap: 'wrap',
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
  },
  dot: { width: 5, height: 5, borderRadius: 3 },
  badgeText: { fontSize: 12, fontWeight: '700' },
  eyebrow: { fontSize: 12, fontWeight: '600', color: colors.textMuted },
  hero: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  symbol: {
    width: 68,
    height: 76,
    borderRadius: 26,
    transform: [{ rotate: '6deg' }],
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroCopy: { flex: 1, gap: 8 },
  kicker: { fontSize: 12, fontWeight: '600' },
  title: {
    fontSize: 23,
    lineHeight: 32,
    fontWeight: '700',
    color: colors.text,
  },
  description: { fontSize: 14, lineHeight: 24, color: colors.textMuted },
  actionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
    paddingTop: 18,
    borderTopWidth: 1,
    borderTopColor: '#E8EFEB',
  },
  actionCopy: { gap: 4, flexShrink: 1 },
  actionTitle: { fontSize: 12, fontWeight: '600', color: colors.text },
  actionHint: { fontSize: 11, lineHeight: 17, color: colors.textMuted },
  primaryButton: {
    minHeight: 48,
    borderRadius: 999,
    paddingVertical: 10,
    paddingLeft: 18,
    paddingRight: 10,
    maxWidth: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  primaryText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
    flexShrink: 1,
  },
  buttonIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#FFFFFF24',
    alignItems: 'center',
    justifyContent: 'center',
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    columnGap: 12,
    alignItems: 'center',
    marginTop: -8,
    marginBottom: -8,
  },
  textButton: {
    minHeight: 44,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingVertical: 10,
  },
  pageCount: { color: colors.textMuted, fontSize: 11, fontWeight: '500' },
  buttonText: { fontSize: 13, lineHeight: 20, fontWeight: '600' },
  empty: { alignItems: 'center', gap: 14, paddingVertical: 18 },
  emptyTitle: {
    color: colors.text,
    fontSize: 18,
    lineHeight: 26,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 4,
  },
  emptyDescription: {
    color: colors.textMuted,
    fontSize: 13,
    lineHeight: 22,
    textAlign: 'center',
  },
  secondaryButton: {
    minHeight: 46,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 999,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  pressed: { opacity: 0.7 },
  disabled: { opacity: 0.55 },
  error: {
    color: colors.danger,
    backgroundColor: '#FFF3F2',
    borderRadius: 12,
    padding: 12,
    fontSize: 13,
    lineHeight: 20,
  },
});
