import { StyleSheet } from 'react-native';
// 작성자: 김진우 — 이전 미션 와이어프레임의 민트·블루 카드와 달력 배치를 사용한다.
export const ms = StyleSheet.create({
  root: { flex: 1 },
  content: {
    padding: 24,
    paddingBottom: 32,
    gap: 18,
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
  },
  row: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  between: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  flex: { flex: 1 },
  header: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  heading: { fontSize: 20, fontWeight: '700', color: '#17342D' },
  title: { fontSize: 22, fontWeight: '700', color: '#17342D' },
  text: { fontSize: 15, fontWeight: '600', color: '#17342D' },
  muted: { fontSize: 12, color: '#718580', lineHeight: 19 },
  green: { fontSize: 13, fontWeight: '600', color: '#049D87' },
  card: {
    padding: 18,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#D7E9E4',
    backgroundColor: '#FFFFFF',
    gap: 14,
    boxShadow: '0px 5px 14px rgba(25,75,63,0.07)',
  },
  track: {
    height: 6,
    backgroundColor: '#CCE8DF',
    borderRadius: 10,
    overflow: 'hidden',
  },
  fill: { height: '100%', backgroundColor: '#26B994', borderRadius: 10 },
  iconButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    backgroundColor: '#FFF',
  },
  week: { flexDirection: 'row', justifyContent: 'space-between' },
  day: {
    flex: 1,
    minHeight: 72,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderRadius: 14,
  },
  date: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selected: { backgroundColor: '#21B78F' },
  selectedCell: { backgroundColor: '#E3F4FF' },
  faded: { opacity: 0.4 },
  white: { color: '#FFF' },
  tiny: { fontSize: 10, color: '#77958D' },
  weekProgress: {
    height: 4,
    width: '75%',
    backgroundColor: '#DDEEE8',
    borderRadius: 5,
    overflow: 'hidden',
  },
  soft: { padding: 16, borderRadius: 18, backgroundColor: '#E8F7F1', gap: 10 },
  mission: {
    padding: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#DAE9E4',
    backgroundColor: '#FFF',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    minHeight: 82,
    boxShadow: '0px 4px 9px rgba(23,52,45,0.06)',
  },
  status: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#DCF7F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusMark: { fontSize: 22, color: '#29AD99' },
  hero: { padding: 22, borderRadius: 24, gap: 12, minHeight: 190 },
  heroTitle: { fontSize: 23, fontWeight: '700', color: '#FFF' },
  heroPercent: {
    fontSize: 28,
    fontWeight: '700',
    color: '#FFF',
    textAlign: 'right',
  },
  heroTrack: {
    height: 10,
    backgroundColor: '#FFFFFF55',
    borderRadius: 10,
    overflow: 'hidden',
  },
  heroFill: { height: '100%', backgroundColor: '#FFF', borderRadius: 10 },
  button: {
    minHeight: 56,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
  },
  buttonText: { color: '#FFF', fontSize: 16, fontWeight: '700' },
  disabled: { backgroundColor: '#D6DEDB' },
  summaryItem: { gap: 7, paddingVertical: 8 },
  smallButton: {
    alignSelf: 'flex-start',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: '#DFF8EC',
  },
  error: { color: '#BB4458', fontSize: 13, lineHeight: 20 },
  calendar: { flexDirection: 'row', flexWrap: 'wrap' },
  cell: {
    width: '14.285714%',
    minHeight: 58,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    borderRadius: 12,
  },
  rate: {
    fontSize: 10,
    color: '#029D86',
    backgroundColor: '#E5F7F1',
    borderRadius: 8,
    paddingHorizontal: 4,
  },
  overlay: {
    flex: 1,
    backgroundColor: '#17342D66',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    padding: 24,
    gap: 20,
    maxHeight: '90%',
  },
  handle: {
    height: 5,
    width: 56,
    backgroundColor: '#D9E8E3',
    borderRadius: 5,
    alignSelf: 'center',
  },
  center: { alignItems: 'center', gap: 10 },
  feedback: {
    flex: 1,
    minHeight: 48,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: '#F3F8F6',
  },
  chosen: { borderColor: '#19B892', backgroundColor: '#EAF9F3' },
});
